#pragma once
#include "core.hpp"
#include <functional>
namespace cn {
class Archive {
    Bytes blob,table;DWORD dataStart,namesStart,filesStart,dirsStart;
    size_t expandedBytes=0;std::set<DWORD> visited;std::set<std::wstring> directoryNames;
    static DWORD u32(const Bytes& b,size_t p){if(p>b.size()||b.size()-p<4)throw std::runtime_error("DXA DWORD bounds");DWORD v;memcpy(&v,b.data()+p,4);return v;}
    static WORD u16(const Bytes& b,size_t p){if(p>b.size()||b.size()-p<2)throw std::runtime_error("DXA WORD bounds");WORD v;memcpy(&v,b.data()+p,2);return v;}
    Bytes decrypt(size_t p,size_t n){const BYTE key[12]={0x92,0xf6,0xe4,0x68,0x9e,0xc1,0x90,0x32,0xcb,0x1e,0,0xa3};if(p>blob.size()||n>blob.size()-p)throw std::runtime_error("DXA encrypted bounds");Bytes out(n);for(size_t i=0;i<n;++i)out[i]=blob[p+i]^key[(p+i)%12];return out;}
    static Bytes lz(const Bytes& b){if(b.size()<9)throw std::runtime_error("DXA compressed header");DWORD expected=u32(b,0),packed=u32(b,4);if(expected>32*1024*1024||packed!=b.size())throw std::runtime_error("DXA compressed size");BYTE escape=b[8];Bytes out;out.reserve(expected);size_t p=9;auto get=[&](){if(p>=b.size())throw std::runtime_error("DXA truncated compressed data");return b[p++];};while(p<b.size()){BYTE v=get();if(v!=escape){if(out.size()>=expected)throw std::runtime_error("DXA decompression overflow");out.push_back(v);continue;}unsigned code=get();if(code==escape){if(out.size()>=expected)throw std::runtime_error("DXA decompression overflow");out.push_back(escape);continue;}if(code>escape)--code;DWORD count=code>>3;if(code&4)count|=get()<<5;count+=4;unsigned size=(code&3)+1;if(size>3)throw std::runtime_error("DXA invalid LZ offset");DWORD distance=0;for(unsigned i=0;i<size;++i)distance|=get()<<(i*8);++distance;if(distance>out.size()||count>expected-out.size())throw std::runtime_error("DXA invalid LZ reference");while(count--)out.push_back(out[out.size()-distance]);}if(out.size()!=expected)throw std::runtime_error("DXA decompression length");return out;}
    void walk(DWORD directory,const std::wstring& prefix,std::map<std::wstring,Bytes>& files){if(std::count(prefix.begin(),prefix.end(),L'/')>64)throw std::runtime_error("DXA directory depth");if(!visited.insert(directory).second||visited.size()>10000)throw std::runtime_error("DXA directory cycle/limit");size_t d=(size_t)dirsStart+directory;DWORD count=u32(table,d+8),first=u32(table,d+12);if(count>10000)throw std::runtime_error("DXA file limit");for(DWORD i=0;i<count;++i){size_t f=(size_t)filesStart+first+(size_t)i*44;DWORD no=u32(table,f),attrs=u32(table,f+4),offset=u32(table,f+32),size=u32(table,f+36),packed=u32(table,f+40);WORD words=u16(table,no);size_t n=(size_t)no+4+(size_t)words*4;if(n>=table.size())throw std::runtime_error("DXA name bounds");size_t end=n;while(end<table.size()&&table[end])++end;if(end==table.size()||end-n>1024)throw std::runtime_error("DXA invalid name");int needed=MultiByteToWideChar(932,MB_ERR_INVALID_CHARS,(char*)table.data()+n,(int)(end-n),0,0);if(!needed)throw std::runtime_error("DXA invalid CP932 name");std::wstring name(needed,0);MultiByteToWideChar(932,MB_ERR_INVALID_CHARS,(char*)table.data()+n,(int)(end-n),name.data(),needed);if(name.empty()||name==L"."||name==L".."||name.find_first_of(L"/\\:")!=name.npos)throw std::runtime_error("DXA unsafe entry");auto path=prefix+name;if(attrs&0x10){directoryNames.insert(path);walk(offset,path+L"/",files);continue;}DWORD amount=packed==0xffffffffu?size:packed;if(size>32*1024*1024||(size_t)dataStart+offset>namesStart||amount>namesStart-((size_t)dataStart+offset))throw std::runtime_error("DXA data bounds");expandedBytes+=size;if(expandedBytes>512u*1024u*1024u)throw std::runtime_error("DXA expanded total exceeds 512 MiB");Bytes b=decrypt((size_t)dataStart+offset,amount);if(packed!=0xffffffffu)b=lz(b);if(b.size()!=size)throw std::runtime_error("DXA file length");if(!files.emplace(path,std::move(b)).second)throw std::runtime_error("DXA duplicate entry");}}
public:
    explicit Archive(const std::wstring& path){if(std::filesystem::file_size(path)>512u*1024u*1024u)throw std::runtime_error("DXA exceeds 512 MiB");auto b=readFile(path);blob.assign(b.begin(),b.end());Bytes h=decrypt(0,28);if(u16(h,0)!=0x5844||u16(h,2)!=4||u32(h,24)!=932)throw std::runtime_error("Expected reviewed MoeKuri DXA v4/CP932");DWORD size=u32(h,4);dataStart=u32(h,8);namesStart=u32(h,12);filesStart=u32(h,16);dirsStart=u32(h,20);table=decrypt(namesStart,size);}
    std::map<std::wstring,Bytes> files(){expandedBytes=0;visited.clear();directoryNames.clear();std::map<std::wstring,Bytes> out;walk(0,L"",out);return out;}
    const std::set<std::wstring>& directories()const{return directoryNames;}
};
inline bool asian(const std::wstring& s){for(wchar_t c:s)if((c>=0x3040&&c<=0x30ff)||(c>=0x3400&&c<=0x9fff)||(c>=0xff61&&c<=0xff9f))return true;return false;}
inline std::wstring archiveText(const Bytes& b){if(b.size()>=2&&b[0]==0xff&&b[1]==0xfe){if(b.size()%2)throw std::runtime_error("Odd UTF-16 archive text");std::wstring w((b.size()-2)/2,0);memcpy(w.data(),b.data()+2,b.size()-2);utf8(w);return w;}return wide(std::string((char*)b.data(),b.size()));}
inline std::vector<std::vector<std::wstring>> csv(const std::wstring& s){std::vector<std::vector<std::wstring>> out;std::vector<std::wstring> row;std::wstring field;bool quotes=false;for(size_t i=0;i<s.size();++i){wchar_t c=s[i];if(c==L'"'){if(quotes&&i+1<s.size()&&s[i+1]==L'"'){field+=c;++i;}else quotes=!quotes;}else if(!quotes&&(c==L','||c==L'\n')){row.push_back(field);field.clear();if(c==L'\n'){out.push_back(row);row.clear();}}else if(c!=L'\r'||quotes)field+=c;}if(quotes)throw std::runtime_error("Unclosed CSV quote");if(!row.empty()||!field.empty()){row.push_back(field);out.push_back(row);}return out;}
inline std::vector<Row> extractAll(const std::wstring& exe,bool omitDxa=false,bool includeExe=true){PE p(readFile(exe));if(hash(std::string((char*)p.b.data(),p.b.size()))!="1c79a2d328d8ccd69765ac624b48f2317d80688c3dc7439ee3c23fc1fc05f847")throw std::runtime_error("请选择未修改的日文 1.10 原版 EXE");if(omitDxa){auto rows=extractExe(p);std::set<std::wstring> blocked;for(const auto& row:extractAll(exe,false,false))blocked.insert(row.source);rows.erase(std::remove_if(rows.begin(),rows.end(),[&](const Row& row){return blocked.count(row.source)!=0;}),rows.end());return rows;}std::map<std::wstring,Row> found;if(includeExe)for(auto& r:extractExe(p))found[r.source]=r;auto add=[&](const std::wstring& s){if(!s.empty()&&s.size()<4096&&asian(s)&&s.find(L'\0')==s.npos)found[s]={s,L"",0};};auto root=std::filesystem::path(exe).parent_path()/L"data";
    for(const wchar_t* archive:{L"dat.dxa",L"csv.dxa",L"etc.dxa"}){auto path=root/archive;if(!std::filesystem::exists(path))continue;Archive a(path.wstring());for(auto& f:a.files()){auto ext=std::filesystem::path(f.first).extension().wstring();if(ext!=L".csv"&&ext!=L".dat"&&ext!=L".txt")continue;std::wstring w;try{w=archiveText(f.second);}catch(const std::exception&){if(ext==L".csv"||f.first.rfind(L"story/",0)==0)throw;continue;}if(w.find(L'\0')!=w.npos)continue;if(ext==L".csv"){for(auto& row:csv(w))for(auto& field:row)add(field);}else if(f.first.rfind(L"story/",0)==0){auto ls=lines(w);for(size_t i=0;i<ls.size();++i){if(ls[i].rfind(L"#txt@",0)!=0)continue;add(ls[i].substr(5));std::wstring body;while(++i<ls.size()&&(ls[i].empty()||ls[i][0]!=L'#')){if(!body.empty())body+=L'\n';body+=ls[i];add(ls[i]);}while(!body.empty()&&(body.back()==L'\r'||body.back()==L'\n'))body.pop_back();add(body);if(i<ls.size())--i;}}else {for(auto& line:lines(w)){if(!line.empty()&&line[0]!=L'#'){add(line);size_t t=line.find(L'\t');if(t!=line.npos)add(line.substr(t+1));}}}}}
    std::vector<Row> out;for(auto& e:found)out.push_back(e.second);return out;
}
inline std::vector<Row> exeOnlyCatalog(const std::wstring& path,const std::vector<Row>& rows){auto filtered=exeCatalog(path,rows);std::set<std::wstring> archiveSources;for(const auto& row:extractAll(path,false,false))archiveSources.insert(row.source);filtered.erase(std::remove_if(filtered.begin(),filtered.end(),[&](const Row& row){return archiveSources.count(row.source)!=0;}),filtered.end());return filtered;}

}
