#pragma once
#include "json.hpp"
#include "font.hpp"
#include "format.h"
#include "compression.hpp"
#include "font_subset.hpp"
#include <bcrypt.h>
#include <set>
#include <sstream>
#include <fstream>
#include <filesystem>
namespace cn {
using namespace moe;
using Bytes=std::vector<BYTE>;
struct Row {std::wstring source,target;DWORD budget=0;};
struct Options {std::wstring font,face=L"Microsoft YaHei";std::string fontMemory;std::wstring extraCharacters;bool subsetFont=true,externalFont=false;LONG height=0,width=0;DWORD charset=134,scale=100,maxWidth=620,minScale=70;};
inline std::string hash(const std::string& b){BCRYPT_ALG_HANDLE a=0;BCRYPT_HASH_HANDLE h=0;DWORD n=0,got=0;BYTE digest[32];if(BCryptOpenAlgorithmProvider(&a,BCRYPT_SHA256_ALGORITHM,0,0)<0)throw std::runtime_error("SHA256 unavailable");BCryptGetProperty(a,BCRYPT_OBJECT_LENGTH,(BYTE*)&n,4,&got,0);Bytes obj(n);bool ok=BCryptCreateHash(a,&h,obj.data(),n,0,0,0)>=0&&BCryptHashData(h,(BYTE*)b.data(),(ULONG)b.size(),0)>=0&&BCryptFinishHash(h,digest,32,0)>=0;if(h)BCryptDestroyHash(h);BCryptCloseAlgorithmProvider(a,0);if(!ok)throw std::runtime_error("SHA256 failed");std::string r;const char* hex="0123456789abcdef";for(auto c:digest){r+=hex[c>>4];r+=hex[c&15];}return r;}
inline DWORD fnv(const std::wstring& s){DWORD h=2166136261u;for(wchar_t c:s){h^=(unsigned short)c;h*=16777619u;}return h;}
inline std::wstring escape(const std::wstring& s){std::wstring r;for(auto c:s){switch(c){case L'\\':r+=L"\\\\";break;case L'\n':r+=L"\\n";break;case L'\r':r+=L"\\r";break;case L'\t':r+=L"\\t";break;default:r+=c;}}return r;}
inline std::wstring unescape(const std::wstring& s){std::wstring r;for(size_t i=0;i<s.size();++i){wchar_t c=s[i];if(c==L'\\'){if(++i==s.size())throw std::runtime_error("Trailing backslash; use \\\\ for a literal backslash");switch(s[i]){case L'n':c=L'\n';break;case L'r':c=L'\r';break;case L't':c=L'\t';break;case L'\\':c=L'\\';break;default:throw std::runtime_error("Unknown TXT escape");}}r+=c;}return r;}
inline std::vector<std::wstring> lines(const std::wstring& s){std::vector<std::wstring> out;size_t p=0;for(;;){size_t q=s.find(L'\n',p);auto l=s.substr(p,q==s.npos?s.npos:q-p);if(!l.empty()&&l.back()==L'\r')l.pop_back();out.push_back(l);if(q==s.npos)break;p=q+1;}return out;}
inline std::wstring tokens(const std::wstring& s){std::wstring r;for(size_t p=0;p<s.size();++p){if(s[p]!=L'%')continue;if(p+1<s.size()&&s[p+1]==L'%'){++p;continue;}size_t q=p+1;while(q<s.size()&&std::wstring(L"-+ #0.123456789hlzLI").find(s[q])!=std::wstring::npos)++q;if(q<s.size()&&std::wstring(L"diuoxXfFeEgGaAcCsS").find(s[q])!=std::wstring::npos){r+=s[q];p=q;}}return r;}
inline void validate(const std::vector<Row>& rows){if(rows.size()>100000)throw std::runtime_error("Too many rows");std::set<std::wstring> seen;for(const auto& r:rows){if(r.source.empty()||r.source.size()>4095||r.target.size()>4095||r.source.find(L'\0')!=r.source.npos||r.target.find(L'\0')!=r.target.npos)throw std::runtime_error("Empty source, embedded NUL or text over 4095 UTF-16 units");if(!seen.insert(r.source).second)throw std::runtime_error("Duplicate source: "+utf8(r.source.substr(0,70)));if(!r.target.empty()&&r.source!=r.target){try{if(tokens(r.source)!=tokens(r.target))throw std::runtime_error("Printf placeholders differ");}catch(const std::exception& e){throw std::runtime_error(std::string(e.what())+": "+utf8(r.source.substr(0,70)));}}if(r.budget>10000)throw std::runtime_error("Invalid pixel budget");utf8(r.source);utf8(r.target);}}
inline std::vector<Row> parse(std::string b){if(b.compare(0,3,"\xef\xbb\xbf")==0)b.erase(0,3);auto w=wide(b);auto first=w.find_first_not_of(L" \t\r\n");std::vector<Row> out;if(first!=w.npos&&w[first]==L'{'){for(const auto& e:JsonParser(b).parse())out.push_back({e.first,e.second,0});}else {for(const auto& l:lines(w)){if(l.empty()||l[0]==L'#')continue;size_t a=l.find(L'\t');if(a==l.npos)throw std::runtime_error("TXT requires source TAB translation [TAB pixel-budget]");size_t z=l.find(L'\t',a+1);if(z!=l.npos&&l.find(L'\t',z+1)!=l.npos)throw std::runtime_error("Too many TXT columns");DWORD budget=0;if(z!=l.npos){auto v=l.substr(z+1);if(v.empty()||v.find_first_not_of(L"0123456789")!=v.npos||v.size()>5)throw std::runtime_error("Invalid pixel budget");budget=(DWORD)std::stoul(v);}out.push_back({unescape(l.substr(0,a)),unescape(l.substr(a+1,z==l.npos?l.npos:z-a-1)),budget});}}validate(out);return out;}
inline std::string serializeRows(const std::vector<Row>& rows){std::wstring out=L"# MoeKuri 1.10 UTF-8 translation TXT v1\n# 原文<TAB>译文<TAB>可选宽度像素; 空译文保留原文; 转义: \\n \\r \\t \\\\\n";for(const auto& r:rows)out+=escape(r.source)+L"\t"+escape(r.target)+L"\t"+std::to_wstring(r.budget)+L"\n";return utf8(out);}
inline void save(const std::wstring& path,const std::string& bytes){if(!writeAtomic(path,bytes))throw std::runtime_error("Cannot save file (Win32 "+std::to_string(GetLastError())+")");}
inline DWORD align(DWORD n,DWORD a){if(!a||(a&(a-1))||n>0xffffffffu-(a-1))throw std::runtime_error("Invalid alignment");return (n+a-1)&~(a-1);}
struct PE {
    Bytes b;mutable Bytes decodedPayload;DWORD ntOff=0,secOff=0;
    explicit PE(const std::string& fileBytes):b(fileBytes.begin(),fileBytes.end()){if(b.size()<64||word(0)!=0x5a4d)throw std::runtime_error("Not a PE");ntOff=dword(60);if(ntOff>b.size()||b.size()-ntOff<248||dword(ntOff)!=0x4550||word(ntOff+4)!=0x14c||word(ntOff+24)!=0x10b||word(ntOff+20)!=224)throw std::runtime_error("Expected x86 PE32");secOff=ntOff+248;if(sections()==0||sections()>64||secOff+sections()*40>b.size())throw std::runtime_error("Invalid PE section table");for(unsigned i=0;i<sections();++i){auto s=section(i);if(s.PointerToRawData>b.size()||s.SizeOfRawData>b.size()-s.PointerToRawData)throw std::runtime_error("Invalid PE raw section bounds");}}
    WORD word(size_t p)const{if(p>b.size()||b.size()-p<2)throw std::runtime_error("Truncated PE word");WORD x;memcpy(&x,b.data()+p,2);return x;}
    DWORD dword(size_t p)const{if(p>b.size()||b.size()-p<4)throw std::runtime_error("Truncated PE DWORD");DWORD x;memcpy(&x,b.data()+p,4);return x;}
    void put32(size_t p,DWORD v){if(p>b.size()||b.size()-p<4)throw std::runtime_error("PE write outside file");memcpy(b.data()+p,&v,4);}
    IMAGE_NT_HEADERS32& nt(){return *(IMAGE_NT_HEADERS32*)(b.data()+ntOff);}
    const IMAGE_NT_HEADERS32& nt()const{return *(const IMAGE_NT_HEADERS32*)(b.data()+ntOff);}
    unsigned sections()const{return word(ntOff+6);}
    IMAGE_SECTION_HEADER section(unsigned i)const{if(i>=sections())throw std::runtime_error("Bad section index");IMAGE_SECTION_HEADER s;memcpy(&s,b.data()+secOff+i*40,40);return s;}
    size_t offset(DWORD rva,size_t n=1)const{for(unsigned i=0;i<sections();++i){auto s=section(i);if(rva>=s.VirtualAddress&&rva-s.VirtualAddress<s.SizeOfRawData){size_t p=s.PointerToRawData+rva-s.VirtualAddress;if(n>s.SizeOfRawData-(rva-s.VirtualAddress)||p>b.size()||n>b.size()-p)throw std::runtime_error("RVA outside raw section");return p;}}if(rva<nt().OptionalHeader.SizeOfHeaders&&rva<=b.size()&&n<=b.size()-rva)return rva;throw std::runtime_error("Unmapped PE RVA");}
    std::string z(DWORD rva)const{size_t p=offset(rva);size_t n=0;while(p+n<b.size()&&b[p+n]&&n<65536)++n;if(p+n>=b.size()||n==65536)throw std::runtime_error("Invalid PE string");return std::string((char*)b.data()+p,n);}
    DWORD nextRva()const{DWORD end=nt().OptionalHeader.SizeOfHeaders;for(unsigned i=0;i<sections();++i){auto s=section(i);if(s.VirtualAddress>0xffffffffu-std::max(s.Misc.VirtualSize,s.SizeOfRawData))throw std::runtime_error("Section overflow");end=std::max(end,s.VirtualAddress+std::max(s.Misc.VirtualSize,s.SizeOfRawData));}return align(end,nt().OptionalHeader.SectionAlignment);}
    void reserveHeaders(unsigned extra){DWORD need=align(secOff+(sections()+extra)*40,nt().OptionalHeader.FileAlignment),old=nt().OptionalHeader.SizeOfHeaders;if(need<=old)return;DWORD delta=need-old;b.insert(b.begin()+old,delta,0);nt().OptionalHeader.SizeOfHeaders=need;for(unsigned i=0;i<sections();++i){auto s=section(i);if(s.PointerToRawData)s.PointerToRawData+=delta;if(s.PointerToRelocations)s.PointerToRelocations+=delta;if(s.PointerToLinenumbers)s.PointerToLinenumbers+=delta;memcpy(b.data()+secOff+i*40,&s,40);}if(nt().FileHeader.PointerToSymbolTable)nt().FileHeader.PointerToSymbolTable+=delta;auto& security=nt().OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_SECURITY];if(security.VirtualAddress)security.VirtualAddress+=delta;auto debug=nt().OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_DEBUG];if(debug.VirtualAddress)for(DWORD p=0;p+sizeof(IMAGE_DEBUG_DIRECTORY)<=debug.Size;p+=sizeof(IMAGE_DEBUG_DIRECTORY)){auto off=offset(debug.VirtualAddress+p,sizeof(IMAGE_DEBUG_DIRECTORY));auto d=(IMAGE_DEBUG_DIRECTORY*)(b.data()+off);if(d->PointerToRawData)d->PointerToRawData+=delta;}}
    DWORD add(const char* name,const Bytes& bytes,DWORD virtualSize,DWORD flags,DWORD rva=0){if(!rva)rva=nextRva();unsigned count=sections();if(secOff+(count+1)*40>nt().OptionalHeader.SizeOfHeaders)throw std::runtime_error("No section header space");DWORD raw=align((DWORD)b.size(),nt().OptionalHeader.FileAlignment),rawSize=align((DWORD)bytes.size(),nt().OptionalHeader.FileAlignment);b.resize(raw+rawSize,0);if(!bytes.empty())memcpy(b.data()+raw,bytes.data(),bytes.size());IMAGE_SECTION_HEADER s{};memcpy(s.Name,name,std::min<size_t>(8,strlen(name)));s.Misc.VirtualSize=virtualSize;s.VirtualAddress=rva;s.SizeOfRawData=rawSize;s.PointerToRawData=rawSize?raw:0; s.Characteristics=flags;memcpy(b.data()+secOff+count*40,&s,40);nt().FileHeader.NumberOfSections=(WORD)(count+1);nt().OptionalHeader.SizeOfImage=align(rva+std::max(virtualSize,rawSize),nt().OptionalHeader.SectionAlignment);return rva;}
};
inline const CNHeader* payload(const PE& p){for(unsigned i=0;i<p.sections();++i){auto s=p.section(i);if(memcmp(s.Name,".cnro",5))continue;if(s.SizeOfRawData<sizeof(CNHeader))throw std::runtime_error("Truncated CN payload");const BYTE* bytesAt=p.b.data()+s.PointerToRawData;SIZE_T available=s.SizeOfRawData;if(!memcmp(bytesAt,"MOECNZ11",8)){if(p.decodedPayload.empty())p.decodedPayload=decompressPayload(bytesAt,available);bytesAt=p.decodedPayload.data();available=p.decodedPayload.size();}auto h=(const CNHeader*)bytesAt;if(memcmp(h->magic,"MOECN110",8)||h->version!=1||h->total>available||h->total<sizeof(CNHeader)||h->count>100000||h->records>h->total||h->count>(h->total-h->records)/sizeof(CNRecord)||h->text>h->total||h->textBytes>h->total-h->text||h->font>h->total||h->fontBytes>h->total-h->font||h->face>=h->total)throw std::runtime_error("Invalid CN payload");
    const char* bytes=(const char*)h;auto stringAt=[&](DWORD offset){if(offset>=h->total)throw std::runtime_error("CN string offset outside payload");const char* end=(const char*)memchr(bytes+offset,0,h->total-offset);if(!end)throw std::runtime_error("Unterminated CN string");return wide(std::string(bytes+offset,end));};if(stringAt(h->face).size()>31)throw std::runtime_error("CN font name too long");
    const auto records=(const CNRecord*)(bytes+h->records);DWORD previous=0;for(DWORD n=0;n<h->count;++n){auto a=stringAt(records[n].source),b=stringAt(records[n].target);if(a.empty()||a.size()>4095||b.size()>4095||fnv(a)!=records[n].hash||(n&&records[n].hash<previous))throw std::runtime_error("Invalid CN lookup record");previous=records[n].hash;}return h;}throw std::runtime_error("No embedded translation section");}
inline std::vector<Row> unpack(const PE& p){auto h=payload(p);return parse(std::string((char*)h+h->text,h->textBytes));}
inline DWORD append(Bytes& b,const std::string& s,bool nul=true){DWORD off=(DWORD)b.size();b.insert(b.end(),s.begin(),s.end());if(nul)b.push_back(0);return off;}
inline Bytes makePayload(const std::vector<Row>& rows,Options opts,const std::string& originalText={}){validate(rows);if(opts.face.size()>31||opts.face.find(L'\0')!=opts.face.npos||opts.height<-64||opts.height>64||opts.width<-32||opts.width>32||opts.scale<25||opts.scale>300||opts.maxWidth>10000||opts.minScale<10||opts.minScale>100)throw std::runtime_error("Invalid font/layout settings");std::map<std::wstring,Row> active;for(auto& r:rows)if(!r.target.empty()&&r.source!=r.target)active[r.source]=r;
    // Exact per-line entries extend coverage to the game's three-line story renderer.
    for(auto& r:rows)if(!r.target.empty()&&r.source!=r.target){auto a=lines(r.source),b=lines(r.target);if(a.size()==b.size()&&a.size()>1)for(size_t i=0;i<a.size();++i)if(!a[i].empty()&&!b[i].empty()&&!active.count(a[i]))active[a[i]]={a[i],b[i],r.budget};}
    std::vector<Row> sorted;for(auto& e:active)sorted.push_back(e.second);std::stable_sort(sorted.begin(),sorted.end(),[](const Row& a,const Row& b){return fnv(a.source)<fnv(b.source);});
    CNHeader h{};memcpy(h.magic,"MOECN110",8);h.version=1;h.count=(DWORD)sorted.size();h.records=sizeof(h);h.height=opts.height;h.width=opts.width;h.charset=opts.charset;h.scale=opts.scale;h.maxWidth=opts.maxWidth;h.minScale=opts.minScale;h.textRva=0x34960;
    Bytes b(sizeof(h)+sorted.size()*sizeof(CNRecord));for(size_t i=0;i<sorted.size();++i){CNRecord r{};r.source=append(b,utf8(sorted[i].source));r.target=append(b,utf8(sorted[i].target));r.hash=fnv(sorted[i].source);r.budget=sorted[i].budget;memcpy(b.data()+h.records+i*sizeof(r),&r,sizeof(r));}
    if(opts.externalFont)h.reserved|=2;std::string font=opts.externalFont?std::string{}:opts.fontMemory;if(!opts.externalFont&&!opts.font.empty())font=readFile(opts.font);if(!font.empty()){opts.face=fontFamily(font);if(opts.face.size()>31)throw std::runtime_error("Font family exceeds 31 characters");bool complex=false;for(const auto& r:rows)for(auto c:r.target)if((USHORT)c>=0x590&&(USHORT)c<=0xeff)complex=true;if(opts.subsetFont&&!complex){std::wstring chars=std::move(opts.extraCharacters);for(auto& r:rows){chars+=r.source;chars+=r.target;}bool reduced=false;font=reduceFont(font,chars,reduced);if(reduced)h.reserved|=1;}}h.face=append(b,utf8(opts.face));auto txt=originalText.empty()?serializeRows(rows):originalText;if(serializeRows(parse(txt))!=serializeRows(rows))throw std::runtime_error("Embedded TXT differs from edited catalog");h.text=append(b,txt,false);h.textBytes=(DWORD)txt.size();h.font=append(b,font,false);h.fontBytes=(DWORD)font.size();h.total=(DWORD)b.size();memcpy(b.data(),&h,sizeof(h));return b;
}
inline std::vector<Row> extractExe(const PE& p){std::set<std::wstring> found;for(unsigned i=0;i<p.sections();++i){auto s=p.section(i);if(memcmp(s.Name,".rdata",6)&&memcmp(s.Name,".data",5))continue;size_t end=s.PointerToRawData+s.SizeOfRawData;for(size_t a=s.PointerToRawData;a+3<end;a+=2){if(a>s.PointerToRawData&&p.word(a-2)!=0)continue;std::wstring w;bool asian=false,valid=true;size_t z=a;for(;z+1<end&&w.size()<4096;z+=2){WORD c=p.word(z);if(!c)break;if((c<32&&c!=9&&c!=10&&c!=13)||(c>=0xd800&&c<=0xdfff)||c>=0xfff0){valid=false;break;}if((c>=0x3040&&c<=0x30ff)||(c>=0x3400&&c<=0x9fff)||(c>=0xff61&&c<=0xff9f))asian=true;w+=c;}if(valid&&z+1<end&&p.word(z)==0&&asian&&!w.empty())found.insert(w);}}
    std::vector<Row> rows;for(auto& s:found)rows.push_back({s,L"",0});return rows;}
}
