#pragma once
#include "pack.hpp"
#include "archive.hpp"
#include "csv.hpp"
#include "language.hpp"
#include <commctrl.h>
#include <commdlg.h>
#include <functional>
#include <thread>
#include <memory>
#include <atomic>
#include <unordered_map>
#include <chrono>
#include <uiautomation.h>
#include <wrl/client.h>
namespace cn::gui {
enum {Open=100,Save,Extract,Unpack,Pack,SelectGame,SelectFont,ClearFont,Apply,Add,Find,OnlyEmpty,Rows,Source,Target,Face,Height,Width,Scale,MaxWidth,MinScale,Budget,ImportCsv,ExportCsv,Language,ExportFont,Previous,Next,OptimizeFont,JumpPage,ExternalFont,OmitDxa};
constexpr UINT Finished=WM_APP+1,FontsReady=WM_APP+2,RunTest=WM_APP+3,TestFinished=WM_APP+4;
enum class Kind {Boot,Open,Extract,Unpack,Pack,Save,Font,Export};
struct Result {Kind kind=Kind::Open;std::vector<Row> rows;std::string raw,font,error;std::wstring path,game,face;Options opts;};
inline HINSTANCE instance;inline HWND window,list,sourceEdit,targetEdit,searchEdit,statusText,gameEdit,fontEdit,faceCombo,heightEdit,widthEdit,scaleEdit,maxEdit,minEdit,budgetEdit,untranslated,languageCombo,progress,pageText,optimizeFont,pageEdit,externalFont,omitDxa;
inline HFONT uiFont;inline std::vector<HFONT> fittedFonts;inline std::vector<Row> rows;inline std::vector<size_t> visible;inline std::unordered_map<std::wstring,size_t> sourceIndex;
inline std::wstring catalogPath,fontPath,rootDir,lastStatus;inline std::string originalCatalog,loadedFont;
inline bool dirty=false,refreshing=false,busy=false,closing=false,fontEnumeration=false,selfTesting=false,editorPending=false;inline int current=-1;inline size_t filled=0;inline ULONGLONG started=0;inline std::wstring testReport;
inline std::shared_ptr<std::atomic_bool> alive;
inline constexpr size_t pageSize=80;
inline size_t pageStart=0;
inline StringMap testMetrics;
struct Caption {HWND hwnd;const wchar_t* key;};inline std::vector<Caption> captions;inline std::vector<HWND> editable;
inline std::wstring text(HWND h){int n=GetWindowTextLengthW(h);std::wstring s(n+1,0);GetWindowTextW(h,s.data(),n+1);s.resize(n);return s;}
inline void set(HWND h,const std::wstring& s){SetWindowTextW(h,s.c_str());}
inline std::wstring moduleDir(){wchar_t p[32768];DWORD n=GetModuleFileNameW(0,p,32768);if(!n||n==32768)throw std::runtime_error("Module path unavailable");return std::filesystem::path(p).parent_path().wstring();}
inline bool isFilled(const Row& r){return !r.target.empty()&&r.target!=r.source;}
inline void status(){if(!statusText)return;std::wstring s=busy?ui::tr(L"busy"):std::wstring(ui::tr(L"total"))+L": "+std::to_wstring(rows.size())+L"  ·  "+ui::tr(L"filled")+L": "+std::to_wstring(filled)+L"  ·  "+ui::tr(L"shown")+L": "+std::to_wstring(visible.size());if(!busy&&dirty)s+=L"  ·  "+std::wstring(ui::tr(L"dirty"));if(!busy&&!lastStatus.empty())s+=L"  ·  "+lastStatus;set(statusText,s);set(window,L"MoeKuri 1.10 "+std::wstring(ui::tr(L"title"))+L" — UTF-8"+(dirty?L" *":L""));}
inline HWND control(const wchar_t* cls,const wchar_t* value,DWORD style,int id,int x,int y,int w,int h,bool edit=false){HWND c=CreateWindowExW((style&WS_BORDER)?WS_EX_CLIENTEDGE:0,cls,value,WS_CHILD|WS_VISIBLE|WS_TABSTOP|style,x,y,w,h,window,(HMENU)(INT_PTR)id,instance,0);SendMessageW(c,WM_SETFONT,(WPARAM)uiFont,TRUE);if(edit)editable.push_back(c);return c;}
inline HWND caption(const wchar_t* cls,const wchar_t* key,DWORD style,int id,int x,int y,int w,int h,bool edit=false){auto c=control(cls,ui::tr(key),style,id,x,y,w,h,edit);captions.push_back({c,key});return c;}
inline void label(const wchar_t* key,int x,int y,int w){caption(L"STATIC",key,0,0,x,y,w,25);}
inline void updateFontMode(){if(!externalFont)return;bool external=SendMessageW(externalFont,BM_GETCHECK,0,0)==BST_CHECKED;for(int id:{SelectFont,ClearFont,OptimizeFont,ExportFont})EnableWindow(GetDlgItem(window,id),!busy&&!external);set(fontEdit,external?std::wstring(ui::tr(L"externalhint")):fontPath.empty()?std::wstring(ui::tr(loadedFont.empty()?L"systemfont":L"retainedfont")):fontPath);}
inline void applyLanguage(){for(auto& c:captions)SendMessageW(c.hwnd,WM_SETFONT,(WPARAM)uiFont,FALSE);for(auto f:fittedFonts)DeleteObject(f);fittedFonts.clear();for(auto& c:captions){set(c.hwnd,ui::tr(c.key));LONG_PTR style=GetWindowLongPtrW(c.hwnd,GWL_EXSTYLE);if(ui::language==8)style|=WS_EX_RTLREADING;else style&=~WS_EX_RTLREADING;SetWindowLongPtrW(c.hwnd,GWL_EXSTYLE,style);
        RECT rect;GetClientRect(c.hwnd,&rect);HDC dc=GetDC(c.hwnd);auto old=SelectObject(dc,uiFont);SIZE size{};GetTextExtentPoint32W(dc,ui::tr(c.key),(int)wcslen(ui::tr(c.key)),&size);SelectObject(dc,old);ReleaseDC(c.hwnd,dc);if(size.cx>rect.right-8){int height=std::max<int>(12,16*(rect.right-8)/std::max(1,(int)size.cx));HFONT font=CreateFontW(-height,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Segoe UI");fittedFonts.push_back(font);SendMessageW(c.hwnd,WM_SETFONT,(WPARAM)font,TRUE);}}
    if(list){LVCOLUMNW col{};col.mask=LVCF_TEXT;col.pszText=(LPWSTR)ui::tr(L"source");ListView_SetColumn(list,0,&col);col.pszText=(LPWSTR)ui::tr(L"target");ListView_SetColumn(list,1,&col);}
    if(fontPath.empty())set(fontEdit,ui::tr(loadedFont.empty()?L"systemfont":L"retainedfont"));updateFontMode();lastStatus.clear();status();
}
inline LONG number(HWND h,LONG low,LONG high){auto s=text(h);size_t used=0;long n;try{n=std::stol(s,&used);}catch(...){throw std::runtime_error(utf8(ui::tr(L"numbers")));}if(used!=s.size()||n<low||n>high)throw std::runtime_error(utf8(ui::tr(L"numbers")));return n;}
inline bool commit(){if(current<0||current>=(int)rows.size()||!editorPending)return false;Row r{text(sourceEdit),text(targetEdit),(DWORD)number(budgetEdit,0,10000)};validate({r});auto other=sourceIndex.find(r.source);if(other!=sourceIndex.end()&&other->second!=(size_t)current)throw std::runtime_error(utf8(ui::tr(L"dup")));auto& previous=rows[current];bool changed=previous.source!=r.source||previous.target!=r.target||previous.budget!=r.budget;if(changed){if(isFilled(previous))--filled;if(isFilled(r))++filled;sourceIndex.erase(previous.source);sourceIndex[r.source]=(size_t)current;previous=std::move(r);originalCatalog.clear();dirty=true;}editorPending=false;return changed;}
inline void indexRows(){sourceIndex.clear();sourceIndex.reserve(rows.size()*2+1);filled=0;for(size_t i=0;i<rows.size();++i){sourceIndex.emplace(rows[i].source,i);if(isFilled(rows[i]))++filled;}}
inline void show(int row){current=row;refreshing=true;editorPending=false;if(row>=0){set(sourceEdit,rows[row].source);set(targetEdit,rows[row].target);set(budgetEdit,std::to_wstring(rows[row].budget));}else {set(sourceEdit,L"");set(targetEdit,L"");set(budgetEdit,L"0");}refreshing=false;}
inline void displayPage(){refreshing=true;if(pageStart>=visible.size())pageStart=visible.empty()?0:((visible.size()-1)/pageSize)*pageSize;size_t count=std::min(pageSize,visible.size()-pageStart);ListView_SetItemCountEx(list,(int)count,LVSICF_NOSCROLL|LVSICF_NOINVALIDATEALL);ListView_SetItemState(list,-1,0,LVIS_SELECTED|LVIS_FOCUSED);if(current>=0){auto p=std::find(visible.begin()+pageStart,visible.begin()+pageStart+count,(size_t)current);if(p!=visible.begin()+pageStart+count)ListView_SetItemState(list,(int)(p-visible.begin()-pageStart),LVIS_SELECTED|LVIS_FOCUSED,LVIS_SELECTED|LVIS_FOCUSED);}set(pageText,std::to_wstring(count?pageStart+1:0)+L" – "+std::to_wstring(pageStart+count)+L" / "+std::to_wstring(visible.size()));EnableWindow(GetDlgItem(window,Previous),!busy&&pageStart>0);EnableWindow(GetDlgItem(window,Next),!busy&&pageStart+count<visible.size());set(pageEdit,std::to_wstring(visible.empty()?0:pageStart/pageSize+1));EnableWindow(pageEdit,!busy&&!visible.empty());EnableWindow(GetDlgItem(window,JumpPage),!busy&&!visible.empty());InvalidateRect(list,0,FALSE);refreshing=false;status();}
inline void populate(){visible.clear();auto query=text(searchEdit);bool only=SendMessageW(untranslated,BM_GETCHECK,0,0)==BST_CHECKED;for(size_t i=0;i<rows.size();++i){auto& r=rows[i];if(only&&isFilled(r))continue;if(!query.empty()&&r.source.find(query)==r.source.npos&&r.target.find(query)==r.target.npos)continue;visible.push_back(i);}displayPage();}
inline void loadRows(Result& r,bool changed){rows=std::move(r.rows);originalCatalog=std::move(r.raw);catalogPath=r.path;dirty=changed;lastStatus.clear();pageStart=0;indexRows();show(-1);populate();}
inline std::wstring filter(const wchar_t* title,const wchar_t* pattern){std::wstring s=title;s.push_back(0);s+=pattern;s.push_back(0);s.push_back(0);return s;}
inline UINT_PTR CALLBACK formatHook(HWND h,UINT m,WPARAM,LPARAM l){if(m==WM_NOTIFY){auto n=(OFNOTIFYW*)l;if(n->hdr.code==CDN_TYPECHANGE){const wchar_t* exts[]={L"txt",L"csv",L"tsv",L"json"};DWORD index=n->lpOFN->nFilterIndex;if(index>=1&&index<=4)SendMessageW(GetParent(h),CDM_SETDEFEXT,0,(LPARAM)exts[index-1]);}}return 0;}
inline std::wstring dialog(bool saving,const std::wstring& filters,const wchar_t* ext,const std::wstring& initial,DWORD* chosen=0){wchar_t p[32768]={0};if(initial.size()<32768)wcscpy_s(p,initial.c_str());OPENFILENAMEW f{};f.lStructSize=sizeof(f);f.hwndOwner=window;f.lpstrFilter=filters.c_str();f.lpstrFile=p;f.nMaxFile=32768;f.lpstrDefExt=ext;f.nFilterIndex=chosen?*chosen:1;f.Flags=OFN_EXPLORER|OFN_NOCHANGEDIR|OFN_PATHMUSTEXIST|(saving?OFN_OVERWRITEPROMPT:OFN_FILEMUSTEXIST);if(saving&&chosen){const wchar_t* exts[]={L"txt",L"csv",L"tsv",L"json"};f.lpstrDefExt=exts[std::min<DWORD>(4,f.nFilterIndex)-1];f.Flags|=OFN_ENABLEHOOK;f.lpfnHook=formatHook;}BOOL ok=saving?GetSaveFileNameW(&f):GetOpenFileNameW(&f);if(!ok){if(CommDlgExtendedError())throw std::runtime_error("File dialog failed");return L"";}if(chosen)*chosen=f.nFilterIndex;return p;}
inline std::wstring saveFilters();
inline std::wstring openFilters(){auto s=filter(ui::tr(L"catalogfilter"),L"*.txt;*.tsv;*.csv;*.json");s.resize(s.size()-1);auto individual=saveFilters();s+=individual;return s;}
inline std::wstring saveFilters(){std::wstring s;for(auto pair:{std::pair<const wchar_t*,const wchar_t*>(L"UTF-8 TXT",L"*.txt"),{L"UTF-8 CSV",L"*.csv"},{L"UTF-8 TSV",L"*.tsv"},{L"UTF-8 JSON",L"*.json"}}){s+=pair.first;s.push_back(0);s+=pair.second;s.push_back(0);}s.push_back(0);return s;}
inline std::string saveFormat(const std::wstring& path,const std::vector<Row>& data){auto ext=catalogExtension(path);if(ext==L".csv")return exportCSV(data);if(ext==L".json"){StringMap m;for(auto& r:data)m[r.source]=r.target;return serialize(m);}return serializeRows(data);}
inline void setBusy(bool value){busy=value;for(HWND c:editable)EnableWindow(c,!value);EnableWindow(pageEdit,!value&&!visible.empty());EnableWindow(GetDlgItem(window,JumpPage),!value&&!visible.empty());EnableWindow(GetDlgItem(window,Previous),!value&&pageStart>0);EnableWindow(GetDlgItem(window,Next),!value&&pageStart+pageSize<visible.size());ShowWindow(progress,value?SW_SHOW:SW_HIDE);SendMessageW(progress,PBM_SETMARQUEE,value,35);updateFontMode();status();}
inline void worker(Kind kind,std::function<Result()> operation){if(busy)return;setBusy(true);auto target=window;auto lifetime=alive;std::thread([kind,operation=std::move(operation),target,lifetime](){auto r=std::make_unique<Result>();r->kind=kind;try{*r=operation();r->kind=kind;}catch(const std::exception& e){r->error=e.what();}catch(...){r->error="Unexpected worker failure";}if(lifetime->load()&&PostMessageW(target,Finished,0,(LPARAM)r.get()))r.release();}).detach();}
inline Options options(){Options o;o.omitDxa=SendMessageW(omitDxa,BM_GETCHECK,0,0)==BST_CHECKED;o.externalFont=SendMessageW(externalFont,BM_GETCHECK,0,0)==BST_CHECKED;o.subsetFont=SendMessageW(optimizeFont,BM_GETCHECK,0,0)==BST_CHECKED;if(!o.externalFont){o.font=fontPath;o.fontMemory=loadedFont;}o.face=text(faceCombo);o.height=number(heightEdit,-64,64);o.width=number(widthEdit,-32,32);o.scale=number(scaleEdit,25,300);o.maxWidth=number(maxEdit,0,10000);o.minScale=number(minEdit,10,100);return o;}
inline void applyOptions(const Options& o){refreshing=true;SendMessageW(omitDxa,BM_SETCHECK,o.omitDxa?BST_CHECKED:BST_UNCHECKED,0);SendMessageW(externalFont,BM_SETCHECK,o.externalFont?BST_CHECKED:BST_UNCHECKED,0);SendMessageW(optimizeFont,BM_SETCHECK,o.subsetFont?BST_CHECKED:BST_UNCHECKED,0);set(faceCombo,o.face);set(heightEdit,std::to_wstring(o.height));set(widthEdit,std::to_wstring(o.width));set(scaleEdit,std::to_wstring(o.scale));set(maxEdit,std::to_wstring(o.maxWidth));set(minEdit,std::to_wstring(o.minScale));refreshing=false;updateFontMode();}
inline bool saveCatalog(bool asynchronous=true){commit();DWORD choice=1;auto currentExt=catalogExtension(catalogPath);if(currentExt==L".csv")choice=2;else if(currentExt==L".tsv")choice=3;else if(currentExt==L".json")choice=4;auto p=dialog(true,saveFilters(),L"txt",catalogPath.empty()?rootDir+L"\\translation.txt":catalogPath,&choice);if(p.empty())return false;if(std::filesystem::path(p).extension().empty()){const wchar_t* ext[]={L".txt",L".csv",L".tsv",L".json"};p+=ext[std::min<DWORD>(choice,4)-1];}auto copy=rows;bool omit=options().omitDxa;auto original=text(gameEdit);auto task=[p,omit,original,data=std::move(copy)]() mutable {Result r;r.path=p;if(omit)data=exeOnlyCatalog(original,data);validate(data);r.raw=saveFormat(p,data);save(p,r.raw);if(catalogExtension(p)==L".csv")r.raw=serializeRows(data);return r;};if(asynchronous){worker(Kind::Save,std::move(task));return true;}auto r=task();catalogPath=p;originalCatalog=catalogExtension(p)==L".json"?serializeRows(rows):r.raw;dirty=false;status();return true;}
inline bool replaceAllowed(){commit();if(!dirty)return true;int answer=MessageBoxW(window,ui::tr(L"saveprompt"),ui::tr(L"save"),MB_YESNOCANCEL|MB_ICONQUESTION);if(answer==IDCANCEL)return false;return answer==IDNO||saveCatalog(false);}
inline int CALLBACK fontEnum(const LOGFONTW* f,const TEXTMETRICW*,DWORD,LPARAM p){if(f->lfFaceName[0]!=L'@')((std::set<std::wstring>*)p)->insert(f->lfFaceName);return 1;}
inline void enumerateFonts(){if(fontEnumeration)return;fontEnumeration=true;auto target=window;auto lifetime=alive;std::thread([target,lifetime](){auto names=std::make_unique<std::set<std::wstring>>();HDC dc=GetDC(0);LOGFONTW lf{};lf.lfCharSet=DEFAULT_CHARSET;EnumFontFamiliesExW(dc,&lf,fontEnum,(LPARAM)names.get(),0);ReleaseDC(0,dc);if(lifetime->load()&&PostMessageW(target,FontsReady,0,(LPARAM)names.get()))names.release();}).detach();}
inline void action(int id){if(busy&&id!=Language)return;switch(id){
case ExternalFont:updateFontMode();break;
case Language:{int selected=(int)SendMessageW(languageCombo,CB_GETCURSEL,0,0);if(selected>=0&&selected<10){ui::language=(size_t)selected;applyLanguage();if(!selfTesting)ui::saveLanguage(rootDir);}break;}
case SelectGame:{auto p=dialog(false,filter(L"EXE",L"*.exe"),L"exe",text(gameEdit));if(!p.empty())set(gameEdit,p);break;}
case SelectFont:{auto p=dialog(false,filter(ui::tr(L"fontfilter"),L"*.ttf;*.otf"),L"ttf",fontPath);if(p.empty())break;worker(Kind::Font,[p](){Result r;r.path=p;r.face=fontFamily(readFile(p));return r;});break;}
case ClearFont:fontPath.clear();loadedFont.clear();set(fontEdit,ui::tr(L"systemfont"));break;
case ExportFont:{auto p=dialog(true,filter(ui::tr(L"fontfilter"),L"*.ttf;*.otf"),L"ttf",rootDir+L"\\exported-font.ttf");if(p.empty())break;auto data=loadedFont;auto path=fontPath;worker(Kind::Export,[p,path,data=std::move(data)](){Result r;r.path=p;auto bytes=path.empty()?data:readFile(path);if(bytes.empty())throw std::runtime_error("No embedded font selected");save(p,bytes);return r;});break;}
case Open:{if(!replaceAllowed())break;auto p=dialog(false,openFilters(),L"txt",catalogPath);if(p.empty())break;worker(Kind::Open,[p](){Result r;r.path=p;auto raw=readFile(p);r.rows=loadCatalog(p,raw);r.raw=catalogExtension(p)==L".csv"?serializeRows(r.rows):raw;return r;});break;}
case Save:saveCatalog();break;
case Extract:{if(!replaceAllowed())break;auto p=text(gameEdit);if(p.empty()){p=dialog(false,filter(L"EXE",L"*.exe"),L"exe",L"");if(p.empty())break;set(gameEdit,p);}auto out=rootDir+L"\\originals.txt";bool omit=options().omitDxa;worker(Kind::Extract,[p,out,omit](){Result r;r.path=out;r.rows=extractAll(p,omit);return r;});break;}
case Unpack:{if(!replaceAllowed())break;auto p=dialog(false,filter(L"EXE",L"*.exe"),L"exe",text(gameEdit));if(p.empty())break;auto out=rootDir+L"\\unpacked.txt";worker(Kind::Unpack,[p,out](){Result r;r.path=out;PE exe(readFile(p));r.rows=unpack(exe);auto h=payload(exe);r.raw=std::string((char*)h+h->text,h->textBytes);r.font=std::string((char*)h+h->font,h->fontBytes);const char* face=(char*)h+h->face;size_t n=0;while(h->face+n<h->total&&face[n])++n;if(h->face+n==h->total)throw std::runtime_error("Unterminated embedded font name");r.opts.face=wide(std::string(face,n));r.opts.subsetFont=(h->reserved&1)!=0;r.opts.externalFont=(h->reserved&2)!=0;r.opts.omitDxa=(h->reserved&4)!=0;r.opts.height=h->height;r.opts.width=h->width;r.opts.scale=h->scale;r.opts.maxWidth=h->maxWidth;r.opts.minScale=h->minScale;return r;});break;}
case Pack:{commit();auto p=text(gameEdit);auto out=dialog(true,filter(L"EXE",L"*.exe"),L"exe",std::filesystem::path(p).parent_path().wstring()+L"\\moekuri_translate.exe");if(out.empty())break;if(std::filesystem::weakly_canonical(p)==std::filesystem::weakly_canonical(out))throw std::runtime_error(utf8(ui::tr(L"overwrite")));auto data=rows;auto opts=options();opts.originalExe=p;auto raw=originalCatalog;worker(Kind::Pack,[p,out,data=std::move(data),opts=std::move(opts),raw=std::move(raw)]() mutable {Result r;r.path=out;if(!opts.externalFont&&opts.subsetFont&&(!opts.font.empty()||!opts.fontMemory.empty()))for(const auto& row:extractAll(p))opts.extraCharacters+=row.source;save(out,pack(readFile(p),data,opts,raw));return r;});break;}
case Apply:commit();populate();break;
case Previous:commit();if(pageStart>=pageSize)pageStart-=pageSize;show(-1);displayPage();ListView_EnsureVisible(list,0,FALSE);break;
case Next:commit();if(pageStart+pageSize<visible.size())pageStart+=pageSize;show(-1);displayPage();ListView_EnsureVisible(list,0,FALSE);break;
case JumpPage:{commit();size_t pages=(visible.size()+pageSize-1)/pageSize;if(pages){LONG page=number(pageEdit,1,(LONG)pages);pageStart=(page-1)*pageSize;show(-1);displayPage();ListView_EnsureVisible(list,0,FALSE);}break;}
case Add:{commit();refreshing=true;set(searchEdit,L"");SendMessageW(untranslated,BM_SETCHECK,BST_UNCHECKED,0);refreshing=false;KillTimer(window,1);std::wstring key=ui::tr(L"newsource");key+=L" "+std::to_wstring(rows.size()+1);while(sourceIndex.count(key))key+=L"+";sourceIndex[key]=rows.size();rows.push_back({key,L"",0});originalCatalog.clear();dirty=true;pageStart=((rows.size()-1)/pageSize)*pageSize;show((int)rows.size()-1);populate();SetFocus(sourceEdit);SendMessageW(sourceEdit,EM_SETSEL,0,-1);break;}
case Find:case OnlyEmpty:commit();pageStart=0;populate();break;
}}
inline void complete(Result& r){setBusy(false);if(!r.error.empty()){if(selfTesting)throw std::runtime_error(r.error);MessageBoxW(window,ui::error(r.error).c_str(),ui::tr(L"failed"),MB_ICONERROR);return;}
    switch(r.kind){case Kind::Boot:loadRows(r,false);if(!r.game.empty())set(gameEdit,r.game);if(!r.opts.font.empty()){fontPath=r.opts.font;set(fontEdit,fontPath);set(faceCombo,r.opts.face);}if(selfTesting)PostMessageW(window,RunTest,0,0);break;
    case Kind::Open:loadRows(r,false);break;
    case Kind::Extract:loadRows(r,true);lastStatus=ui::tr(L"extractdone");status();break;
    case Kind::Unpack:loadedFont=std::move(r.font);fontPath.clear();applyOptions(r.opts);updateFontMode();loadRows(r,true);break;
    case Kind::Pack:MessageBoxW(window,(std::wstring(ui::tr(L"packdone"))+L"\n\n"+r.path).c_str(),ui::tr(L"done"),MB_OK);break;
    case Kind::Save:catalogPath=r.path;originalCatalog=serializeRows(rows);dirty=false;lastStatus=ui::tr(L"done");status();break;
    case Kind::Font:fontPath=r.path;loadedFont.clear();set(fontEdit,r.path);set(faceCombo,r.face);break;
    case Kind::Export:lastStatus=ui::tr(L"done");status();break;
    }
    if(closing)PostMessageW(window,WM_CLOSE,0,0);
}
inline void guiTest(){
    ULONGLONG ready=GetTickCount64()-started,start=GetTickCount64();if(!options().omitDxa)throw std::runtime_error("DXA exclusion must default on");auto restore=options();SendMessageW(omitDxa,BM_SETCHECK,BST_UNCHECKED,0);if(options().omitDxa)throw std::runtime_error("DXA option cannot be disabled");applyOptions(restore);if(!options().omitDxa)throw std::runtime_error("DXA option restore failed");
    if(GetDlgItem(window,ImportCsv)||GetDlgItem(window,ExportCsv))throw std::runtime_error("CSV buttons were not merged");if(SendMessageW(optimizeFont,BM_GETCHECK,0,0)!=BST_CHECKED)throw std::runtime_error("Font optimization is not enabled by default");
    if(SendMessageW(externalFont,BM_GETCHECK,0,0)!=BST_UNCHECKED)throw std::runtime_error("External font must default off");auto originalOptions=options();SendMessageW(externalFont,BM_SETCHECK,BST_CHECKED,0);action(ExternalFont);auto externalOptions=options();if(!externalOptions.externalFont||!externalOptions.font.empty()||!externalOptions.fontMemory.empty()||IsWindowEnabled(GetDlgItem(window,SelectFont))||IsWindowEnabled(optimizeFont))throw std::runtime_error("External font mode did not disable embedding");applyOptions(originalOptions);if(options().externalFont||!IsWindowEnabled(optimizeFont))throw std::runtime_error("External font settings restore failed");
    int nativeCount=ListView_GetItemCount(list);
    if(nativeCount!=(int)std::min(pageSize,rows.size()))throw std::runtime_error("Unbounded native list");
    for(int i=0;i<100&&nativeCount;++i){ListView_SetItemState(list,i%nativeCount,LVIS_SELECTED|LVIS_FOCUSED,LVIS_SELECTED|LVIS_FOCUSED);if(current!=(int)visible[i%nativeCount])throw std::runtime_error("Row selection mapping failed");auto original=rows[current].target;set(targetEdit,original.empty()?rows[current].source+L" test":original+L" test");SendMessageW(window,WM_COMMAND,MAKEWPARAM(Target,EN_CHANGE),(LPARAM)targetEdit);action(Apply);if(rows[current].target==original)throw std::runtime_error("Row edit was not saved");set(targetEdit,original);SendMessageW(window,WM_COMMAND,MAKEWPARAM(Target,EN_CHANGE),(LPARAM)targetEdit);action(Apply);}
    ULONGLONG clicks=GetTickCount64()-start;start=GetTickCount64();
    for(int i=0;i<100;++i){SendMessageW(list,WM_VSCROLL,SB_BOTTOM,0);UpdateWindow(list);SendMessageW(list,WM_VSCROLL,SB_TOP,0);UpdateWindow(list);}
    while(pageStart+pageSize<visible.size()){action(Next);ListView_SetItemState(list,0,LVIS_SELECTED|LVIS_FOCUSED,LVIS_SELECTED|LVIS_FOCUSED);if(current!=(int)visible[pageStart])throw std::runtime_error("Page selection mapping failed");if(ListView_GetItemCount(list)>(int)pageSize)throw std::runtime_error("Oversized page");}
    while(pageStart){action(Previous);}
    size_t lastPage=(visible.size()+pageSize-1)/pageSize;set(pageEdit,std::to_wstring(lastPage));action(JumpPage);if(pageStart!=(lastPage-1)*pageSize)throw std::runtime_error("Last page jump failed");if(lastPage>1){set(pageEdit,L"2");SendMessageW(pageEdit,WM_KEYDOWN,VK_RETURN,0);MSG jump{};if(!PeekMessageW(&jump,window,WM_COMMAND,WM_COMMAND,PM_REMOVE))throw std::runtime_error("Enter did not request a page jump");DispatchMessageW(&jump);if(pageStart!=pageSize)throw std::runtime_error("Enter page jump failed");}set(pageEdit,L"1");action(JumpPage);if(pageStart!=0)throw std::runtime_error("First page jump failed");
    ULONGLONG paging=GetTickCount64()-start;start=GetTickCount64();
    for(size_t language=0;language<10;++language){ui::language=language;applyLanguage();if(text(GetDlgItem(window,Pack))!=ui::tr(L"pack"))throw std::runtime_error("Localized pack button mismatch");for(const auto& e:ui::catalog())for(auto t:e.second)if(!t||!*t)throw std::runtime_error("Missing translation");}
    ULONGLONG switching=GetTickCount64()-start;set(searchEdit,L"%d");KillTimer(window,1);action(Find);auto count=visible.size();set(searchEdit,L"");KillTimer(window,1);action(Find);
    auto csv=exportCSV(rows);if(serializeRows(importCSV(csv))!=serializeRows(rows))throw std::runtime_error("GUI CSV roundtrip failed");
    testMetrics={{L"omit_dxa_default",L"true"},{L"gui_passed",L"true"},{L"merged_import_export",L"true"},{L"page_jump",L"true"},{L"font_optimization_default",L"true"},{L"virtual_list",L"true"},{L"page_size",std::to_wstring(pageSize)},{L"native_items",std::to_wstring(nativeCount)},{L"rows",std::to_wstring(rows.size())},{L"ready_ms",std::to_wstring(ready)},{L"selection_and_apply_100_ms",std::to_wstring(clicks)},{L"scroll_100_and_all_pages_ms",std::to_wstring(paging)},{L"language_switch_10_ms",std::to_wstring(switching)},{L"languages",L"10"},{L"filtered_rows",std::to_wstring(count)},{L"csv_roundtrip",L"true"}};
    // The UI thread must pump while the Windows accessibility provider is queried.
    auto target=window;auto lifetime=alive;auto listHandle=list;
    std::thread([target,lifetime,listHandle](){
        auto r=std::make_unique<Result>();ULONGLONG begin=GetTickCount64();HRESULT hr=CoInitializeEx(0,COINIT_MULTITHREADED);
        try{
            if(FAILED(hr))throw std::runtime_error("UIA COM initialization failed");
            using Microsoft::WRL::ComPtr;ComPtr<IUIAutomation> uia;ComPtr<IUIAutomationElement> element;ComPtr<IUIAutomationCondition> condition;ComPtr<IUIAutomationCacheRequest> cache;ComPtr<IUIAutomationElementArray> elements;
            auto checked=[](HRESULT value){if(FAILED(value))throw std::runtime_error("Windows accessibility traversal failed");};
            checked(CoCreateInstance(__uuidof(CUIAutomation),0,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&uia)));checked(uia->ElementFromHandle(listHandle,&element));checked(uia->CreateTrueCondition(&condition));checked(uia->CreateCacheRequest(&cache));
            checked(cache->AddProperty(UIA_NamePropertyId));checked(cache->AddProperty(UIA_ControlTypePropertyId));checked(cache->AddProperty(UIA_IsOffscreenPropertyId));checked(cache->AddPattern(UIA_SelectionItemPatternId));
            checked(element->FindAllBuildCache(TreeScope_Descendants,condition.Get(),cache.Get(),&elements));int length=0,items=0;checked(elements->get_Length(&length));
            for(int i=0;i<length;++i){ComPtr<IUIAutomationElement> e;CONTROLTYPEID type=0;checked(elements->GetElement(i,&e));checked(e->get_CachedControlType(&type));if(type==UIA_ListItemControlTypeId)++items;}
            if(items!=(int)pageSize||length>1000)throw std::runtime_error("Accessibility page bound failed");
            r->raw=std::to_string(GetTickCount64()-begin);r->font=std::to_string(length);r->face=std::to_wstring(items);
        }catch(const std::exception& e){r->error=e.what();}
        if(SUCCEEDED(hr))CoUninitialize();if(lifetime->load()&&PostMessageW(target,TestFinished,0,(LPARAM)r.get()))r.release();
    }).detach();
}
inline LRESULT CALLBACK procedure(HWND h,UINT m,WPARAM w,LPARAM l){try{switch(m){
case WM_COMMAND:{int id=LOWORD(w),code=HIWORD(w);if(!refreshing&&current>=0&&(id==Source||id==Target||id==Budget)&&code==EN_CHANGE){editorPending=true;dirty=true;lastStatus.clear();status();}else if(id==Find&&code==EN_CHANGE){KillTimer(h,1);SetTimer(h,1,180,0);}else if(id==Language&&code==CBN_SELCHANGE)action(Language);else if(id==Face&&code==CBN_DROPDOWN)enumerateFonts();else if(code==BN_CLICKED)action(id);return 0;}
case WM_TIMER:if(w==1){KillTimer(h,1);if(!busy)action(Find);}return 0;
case WM_NOTIFY:{auto n=(NMHDR*)l;if(n->idFrom==Rows&&n->code==LVN_GETDISPINFOW){auto info=(NMLVDISPINFOW*)l;if((info->item.mask&LVIF_TEXT)&&info->item.iItem>=0&&(size_t)info->item.iItem<pageSize&&(size_t)info->item.iItem+pageStart<visible.size()){auto& r=rows[visible[pageStart+info->item.iItem]];auto s=escape(info->item.iSubItem?r.target:r.source);if(info->item.pszText&&info->item.cchTextMax>0)wcsncpy_s(info->item.pszText,info->item.cchTextMax,s.c_str(),_TRUNCATE);}return 0;}if(n->idFrom==Rows&&n->code==LVN_ITEMCHANGED&&!refreshing){auto item=(NMLISTVIEW*)l;if((item->uChanged&LVIF_STATE)&&(item->uNewState&LVIS_SELECTED)&&item->iItem>=0&&(size_t)item->iItem<pageSize&&(size_t)item->iItem+pageStart<visible.size()){commit();show((int)visible[pageStart+item->iItem]);status();}}return 0;}
case Finished:{std::unique_ptr<Result> r((Result*)l);complete(*r);return 0;}
case FontsReady:{std::unique_ptr<std::set<std::wstring>> fonts((std::set<std::wstring>*)l);auto face=text(faceCombo);SendMessageW(faceCombo,WM_SETREDRAW,FALSE,0);SendMessageW(faceCombo,CB_RESETCONTENT,0,0);for(auto& s:*fonts)SendMessageW(faceCombo,CB_ADDSTRING,0,(LPARAM)s.c_str());set(faceCombo,face);SendMessageW(faceCombo,WM_SETREDRAW,TRUE,0);InvalidateRect(faceCombo,0,TRUE);return 0;}
case RunTest:guiTest();return 0;
case TestFinished:{std::unique_ptr<Result> r((Result*)l);if(!r->error.empty())throw std::runtime_error(r->error);testMetrics[L"accessibility_bulk_passed"]=L"true";testMetrics[L"accessibility_ms"]=wide(r->raw);testMetrics[L"accessibility_nodes"]=wide(r->font);testMetrics[L"accessibility_items"]=r->face;save(testReport,serialize(testMetrics));dirty=false;DestroyWindow(h);return 0;}
case WM_CLOSE:if(busy){closing=true;return 0;}if(replaceAllowed())DestroyWindow(h);return 0;
case WM_DESTROY:alive->store(false);PostQuitMessage(0);return 0;
}return DefWindowProcW(h,m,w,l);}catch(const std::exception& e){if(selfTesting){save(testReport,serialize({{L"gui_passed",L"false"},{L"error",wide(e.what())}}));dirty=false;busy=false;DestroyWindow(h);}else MessageBoxW(h,ui::error(e.what()).c_str(),ui::tr(L"failed"),MB_ICONERROR);return 0;}}
inline LRESULT CALLBACK pageKey(HWND h,UINT m,WPARAM w,LPARAM l,UINT_PTR,DWORD_PTR){if(m==WM_GETDLGCODE){auto msg=(MSG*)l;if(msg&&msg->message==WM_KEYDOWN&&msg->wParam==VK_RETURN)return DLGC_WANTALLKEYS;return DefSubclassProc(h,m,w,l);}if(m==WM_KEYDOWN&&w==VK_RETURN){PostMessageW(window,WM_COMMAND,MAKEWPARAM(JumpPage,BN_CLICKED),0);return 0;}if(m==WM_CHAR&&w==VK_RETURN)return 0;return DefSubclassProc(h,m,w,l);}
inline void run(HINSTANCE app,const std::wstring& report=L""){instance=app;rootDir=moduleDir();selfTesting=!report.empty();testReport=report;started=GetTickCount64();alive=std::make_shared<std::atomic_bool>(true);ui::loadLanguage(rootDir);INITCOMMONCONTROLSEX common{sizeof(common),ICC_LISTVIEW_CLASSES|ICC_PROGRESS_CLASS};InitCommonControlsEx(&common);uiFont=CreateFontW(-16,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Segoe UI");WNDCLASSW cls{};cls.hInstance=instance;cls.lpszClassName=L"MoeKuriTranslationToolsV2";cls.lpfnWndProc=procedure;cls.hCursor=LoadCursorW(0,IDC_ARROW);cls.hIcon=LoadIconW(0,IDI_APPLICATION);cls.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&cls);window=CreateWindowExW(0,cls.lpszClassName,L"MoeKuri 1.10",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX,CW_USEDEFAULT,CW_USEDEFAULT,1180,860,0,0,instance,0);if(!window)throw std::runtime_error("Cannot create tool window");
    const wchar_t* keys[]={L"open",L"save",L"extract",L"unpack",L"pack"};int ids[]={Open,Save,Extract,Unpack,Pack};for(int i=0;i<5;++i)caption(L"BUTTON",keys[i],BS_PUSHBUTTON,ids[i],16+i*174,16,166,34,true);languageCombo=control(L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_VSCROLL,Language,904,16,224,350);for(auto s:ui::names)SendMessageW(languageCombo,CB_ADDSTRING,0,(LPARAM)s);SendMessageW(languageCombo,CB_SETCURSEL,ui::language,0);
    label(L"game",16,66,140);gameEdit=control(L"EDIT",L"",ES_AUTOHSCROLL|WS_BORDER,0,162,62,800,30,true);caption(L"BUTTON",L"browse",BS_PUSHBUTTON,SelectGame,978,62,150,30,true);
    label(L"font",16,108,140);fontEdit=control(L"EDIT",ui::tr(L"systemfont"),ES_READONLY|ES_AUTOHSCROLL|WS_BORDER,0,162,104,620,30);caption(L"BUTTON",L"choosefont",BS_PUSHBUTTON,SelectFont,794,104,168,30,true);caption(L"BUTTON",L"clearfont",BS_PUSHBUTTON,ClearFont,978,104,150,30,true);
    label(L"face",16,152,140);faceCombo=control(L"COMBOBOX",L"",CBS_DROPDOWN|CBS_AUTOHSCROLL|WS_VSCROLL,Face,162,148,300,400,true);for(auto f:{L"Microsoft YaHei",L"SimSun",L"Segoe UI",L"Arial",L"Xiaolai"})SendMessageW(faceCombo,CB_ADDSTRING,0,(LPARAM)f);set(faceCombo,L"Microsoft YaHei");
    label(L"height",490,152,86);heightEdit=control(L"EDIT",L"0",WS_BORDER|ES_AUTOHSCROLL,Height,578,148,68,30,true);label(L"width",668,152,86);widthEdit=control(L"EDIT",L"0",WS_BORDER|ES_AUTOHSCROLL,Width,754,148,68,30,true);label(L"scale",844,152,100);scaleEdit=control(L"EDIT",L"100",WS_BORDER|ES_AUTOHSCROLL,Scale,950,148,78,30,true);
    label(L"maxwidth",16,196,140);maxEdit=control(L"EDIT",L"620",WS_BORDER|ES_AUTOHSCROLL,MaxWidth,162,192,90,30,true);label(L"minscale",278,196,156);minEdit=control(L"EDIT",L"70",WS_BORDER|ES_AUTOHSCROLL,MinScale,438,192,80,30,true);label(L"layoutnote",548,196,580);
    caption(L"BUTTON",L"exportfont",BS_PUSHBUTTON,ExportFont,16,236,174,32,true);optimizeFont=caption(L"BUTTON",L"optimizefont",BS_AUTOCHECKBOX,OptimizeFont,204,236,470,32,true);SendMessageW(optimizeFont,BM_SETCHECK,BST_CHECKED,0);externalFont=caption(L"BUTTON",L"externalfont",BS_AUTOCHECKBOX,ExternalFont,690,236,438,32,true);omitDxa=caption(L"BUTTON",L"omitdxa",BS_AUTOCHECKBOX,OmitDxa,16,270,442,24,true);SendMessageW(omitDxa,BM_SETCHECK,BST_CHECKED,0);label(L"externalhint",468,270,660);
    label(L"search",16,294,210);searchEdit=control(L"EDIT",L"",WS_BORDER|ES_AUTOHSCROLL,Find,230,290,310,30,true);untranslated=caption(L"BUTTON",L"empty",BS_AUTOCHECKBOX,OnlyEmpty,556,290,190,30,true);caption(L"BUTTON",L"add",BS_PUSHBUTTON,Add,762,290,152,30,true);
    list=control(WC_LISTVIEWW,L"",WS_BORDER|LVS_REPORT|LVS_OWNERDATA|LVS_SINGLESEL|LVS_SHOWSELALWAYS,Rows,16,334,670,408,true);ListView_SetExtendedListViewStyle(list,LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER|LVS_EX_GRIDLINES);LVCOLUMNW column{};column.mask=LVCF_TEXT|LVCF_WIDTH;column.cx=310;column.pszText=(LPWSTR)ui::tr(L"source");ListView_InsertColumn(list,0,&column);column.pszText=(LPWSTR)ui::tr(L"target");column.cx=310;ListView_InsertColumn(list,1,&column);
    caption(L"BUTTON",L"previous",BS_PUSHBUTTON,Previous,16,750,108,30,true);caption(L"BUTTON",L"next",BS_PUSHBUTTON,Next,136,750,108,30,true);pageText=control(L"STATIC",L"",0,0,264,755,190,25);label(L"page",464,755,48);pageEdit=control(L"EDIT",L"1",WS_BORDER|ES_NUMBER|ES_AUTOHSCROLL,0,514,750,64,30,true);SetWindowSubclass(pageEdit,pageKey,1,0);caption(L"BUTTON",L"jump",BS_PUSHBUTTON,JumpPage,590,750,96,30,true);
    label(L"sourcehint",704,334,426);sourceEdit=control(L"EDIT",L"",WS_BORDER|ES_MULTILINE|ES_AUTOVSCROLL|WS_VSCROLL|ES_WANTRETURN,Source,704,360,426,126,true);label(L"targethint",704,494,426);targetEdit=control(L"EDIT",L"",WS_BORDER|ES_MULTILINE|ES_AUTOVSCROLL|WS_VSCROLL|ES_WANTRETURN,Target,704,520,426,196,true);SendMessageW(sourceEdit,EM_SETLIMITTEXT,32768,0);SendMessageW(targetEdit,EM_SETLIMITTEXT,32768,0);label(L"budget",704,742,245);budgetEdit=control(L"EDIT",L"0",WS_BORDER|ES_AUTOHSCROLL,Budget,954,738,70,30,true);caption(L"BUTTON",L"apply",BS_PUSHBUTTON,Apply,1036,738,94,30,true);statusText=control(L"STATIC",L"",0,0,16,790,950,28);progress=control(PROGRESS_CLASSW,L"",PBS_MARQUEE,0,988,794,142,16);applyLanguage();
    ShowWindow(window,selfTesting?SW_HIDE:SW_SHOW);UpdateWindow(window);
    auto dir=rootDir;worker(Kind::Boot,[dir](){Result r;auto seed=dir+L"\\translation.txt";if(!std::filesystem::exists(seed))seed=dir+L"\\1.10trans.txt";if(std::filesystem::exists(seed)){r.path=seed;r.raw=readFile(seed);r.rows=parse(r.raw);}auto base=std::filesystem::path(dir).parent_path();std::error_code ec;for(auto& file:std::filesystem::directory_iterator(base,ec)){if(file.path().extension()==L".exe"&&file.file_size(ec)==4358144){if(hash(readFile(file.path().wstring()))=="1c79a2d328d8ccd69765ac624b48f2317d80688c3dc7439ee3c23fc1fc05f847"){r.game=file.path().wstring();break;}}}auto font=dir+L"\\font.ttf";if(std::filesystem::exists(font)){r.opts.font=font;r.opts.face=fontFamily(readFile(font));}return r;});
    MSG msg;while(GetMessageW(&msg,0,0,0)>0){if(!IsDialogMessageW(window,&msg)){TranslateMessage(&msg);DispatchMessageW(&msg);}}for(auto f:fittedFonts)DeleteObject(f);DeleteObject(uiFont);
}
}
