#include "gui.hpp"
#include <shellapi.h>
#include <cstdio>
using namespace cn;
namespace {
void output(const std::string& s){DWORD n;HANDLE h=GetStdHandle(STD_OUTPUT_HANDLE);if(h&&h!=INVALID_HANDLE_VALUE)WriteFile(h,s.data(),(DWORD)s.size(),&n,0);}
Options cliOptions(int n,wchar_t** args,int start){Options o;for(int i=start;i<n;++i){std::wstring k=args[i];if(i+1>=n)throw std::runtime_error("Missing option value");std::wstring v=args[++i];if(k==L"--font-dxa"){if(v!=L"0"&&v!=L"1")throw std::runtime_error("--font-dxa requires 0 or 1");o.fontDxa=v==L"1";if(o.fontDxa)o.externalFont=true;}else if(k==L"--omit-dxa"){if(v!=L"0"&&v!=L"1")throw std::runtime_error("--omit-dxa requires 0 or 1");o.omitDxa=v==L"1";}else if(k==L"--external-font"){if(v!=L"0"&&v!=L"1")throw std::runtime_error("--external-font requires 0 or 1");o.externalFont=v==L"1";}else if(k==L"--subset-font"){if(v!=L"0"&&v!=L"1")throw std::runtime_error("--subset-font requires 0 or 1");o.subsetFont=v==L"1";}else if(k==L"--font")o.font=v;else if(k==L"--face")o.face=v;else if(k==L"--height")o.height=std::stol(v);else if(k==L"--width")o.width=std::stol(v);else if(k==L"--scale")o.scale=std::stoul(v);else if(k==L"--max-width")o.maxWidth=std::stoul(v);else if(k==L"--min-scale")o.minScale=std::stoul(v);else throw std::runtime_error("Unknown option");}if(o.fontDxa)o.externalFont=true;return o;}
void selfTest(){std::vector<Row> sample={{L"短い文",L"这是比原文长得多的中文测试文本，用于验证新区段。",230},{L"数字 %02d / %s",L"数值 %02d / %s",0},{L"改行\nタブ\t斜線\\",L"换行\n制表\t反斜线\\",0}};auto b=serializeRows(sample);auto parsed=parse(b);if(serializeRows(parsed)!=b)throw std::runtime_error("TXT roundtrip");Options full;full.omitDxa=false;auto ro=makePayload(sample,full);auto h=(const CNHeader*)ro.data();if(h->count!=5||std::string((char*)h+h->text,h->textBytes)!=b)throw std::runtime_error("Payload roundtrip");auto compressed=compressPayload(ro);if(decompressPayload(compressed.data(),compressed.size())!=ro)throw std::runtime_error("Compressed payload roundtrip");auto invalid=compressed;((CNCompressedHeader*)invalid.data())->rawBytes=0xffffffffu;bool boundsRejected=false;try{decompressPayload(invalid.data(),invalid.size());}catch(...){boundsRejected=true;}if(!boundsRejected)throw std::runtime_error("Compressed size bounds not checked");invalid=compressed;((CNCompressedHeader*)invalid.data())->checksum^=1;bool corruptRejected=false;try{decompressPayload(invalid.data(),invalid.size());}catch(...){corruptRejected=true;}if(!corruptRejected)throw std::runtime_error("Compressed checksum not checked");for(const auto& bad:{std::string("\xff\tbad\n"),std::string("x\ta\nx\tb\n"),std::string("%d\t%s\n"),std::string("x\tbad\\q\n")}){bool rejected=false;try{parse(bad);}catch(...){rejected=true;}if(!rejected)throw std::runtime_error("Invalid catalog accepted");}auto csvSample=sample;csvSample.push_back({L"Comma, quotes \" newline\r\nTAB\t\\",L"Comma, \" translated\r\nTAB\t\\",123});if(serializeRows(importCSV(exportCSV(csvSample)))!=serializeRows(csvSample))throw std::runtime_error("CSV multiline roundtrip");
    auto protectedPayload=makePayload({{L"@ブラリボン",L"@布拉玛（缎带）",0},{L"ブラリボン",L"布拉玛（缎带）",0}},Options{});auto protectedHeader=(const CNHeader*)protectedPayload.data();if(protectedHeader->count!=1)throw std::runtime_error("Script identifier entered lookup table");auto record=(const CNRecord*)(protectedPayload.data()+protectedHeader->records);if(wide((const char*)protectedPayload.data()+record->source)!=L"ブラリボン")throw std::runtime_error("Visible character name lost");
    for(const auto& badCsv:{std::string("Original,Translation\n\"unclosed,x"),std::string("Original,Translation\nx\"y,z\n"),std::string("Original,Translation\n\"x\"oops,y\n"),std::string("A,B\nx,y\n")}){bool rejected=false;try{importCSV(badCsv);}catch(...){rejected=true;}if(!rejected)throw std::runtime_error("Invalid CSV accepted");}
    for(size_t i=0;i<10;++i){const WORD ids[]={LANG_CHINESE,LANG_ENGLISH,LANG_KOREAN,LANG_FRENCH,LANG_JAPANESE,LANG_ITALIAN,LANG_GERMAN,LANG_RUSSIAN,LANG_ARABIC,LANG_SPANISH};if(ui::systemLanguage(MAKELANGID(ids[i],SUBLANG_DEFAULT))!=i)throw std::runtime_error("System language detection failed");}
    output("{\"self_test\":true,\"compression_roundtrip\":true,\"compressed_bounds_and_checksum\":true,\"utf8\":true,\"long_text\":true,\"csv_multiline\":true,\"system_languages_10\":true,\"escapes\":true,\"invalid_inputs_rejected\":true}\n");}
int cli(int n,wchar_t** a){std::wstring command=a[1];if(command==L"--self-test"){selfTest();return 0;}
    if(command==L"--dxa-unpack"&&n==4){auto count=unpackArchive(a[2],a[3]);output("{\"dxa_unpacked\":true,\"files\":"+std::to_string(count)+"}\n");return 0;}
    if(command==L"--dxa-pack"&&n==4){auto count=packArchive(a[2],a[3]);output("{\"dxa_packed\":true,\"files\":"+std::to_string(count)+"}\n");return 0;}
    if(command==L"--font-archive"&&n==4){save(a[3],fontArchive(readFile(a[2])));output("{\"font_archive\":true}\n");return 0;}
    if(command==L"--inspect"&&n==3){PE exe(readFile(a[2]));auto info=markerInfo(exe);if(info.empty()){output("{\"marked\":false}\n");return 0;}auto h=payload(exe);info[L"marked"]=L"true";info[L"catalog_sha256_matches"]=wide(hash(std::string((char*)h+h->text,h->textBytes)))==info[L"catalog_sha256"]?L"true":L"false";output(serialize(info));return 0;}
    if(command==L"--language-list"){StringMap m;for(size_t i=0;i<ui::codes.size();++i)m[ui::codes[i]]=ui::names[i];m[L"system_default"]=ui::codes[ui::systemLanguage(GetUserDefaultUILanguage())];output(serialize(m));return 0;}
    if((command==L"--import-csv"||command==L"--export-csv"||command==L"--convert")&&n==4){auto raw=readFile(a[2]);auto r=command==L"--import-csv"?importCSV(raw):loadCatalog(a[2],raw);auto bytes=command==L"--export-csv"?exportCSV(r):gui::saveFormat(a[3],r);save(a[3],bytes);output("{\"converted\":true,\"rows\":"+std::to_string(r.size())+"}\n");return 0;}
    if(command==L"--filter-exe"&&n==5){auto r=exeOnlyCatalog(a[2],loadCatalog(a[3],readFile(a[3])));save(a[4],gui::saveFormat(a[4],r));output("{\"filtered\":true,\"rows\":"+std::to_string(r.size())+"}\n");return 0;}if(command==L"--validate"&&n==3){auto raw=readFile(a[2]);auto r=loadCatalog(a[2],raw);output("{\"valid\":true,\"rows\":"+std::to_string(r.size())+"}\n");return 0;}if(command==L"--extract"&&n>=4){auto opts=cliOptions(n,a,4);auto r=extractAll(a[2],opts.omitDxa);save(a[3],gui::saveFormat(a[3],r));output("{\"extracted\":"+std::to_string(r.size())+"}\n");return 0;}
    if(command==L"--pack"&&n>=5){if(std::filesystem::weakly_canonical(a[2])==std::filesystem::weakly_canonical(a[4]))throw std::runtime_error("Refusing to overwrite original EXE");auto raw=readFile(a[3]);auto r=loadCatalog(a[3],raw);auto ext=catalogExtension(a[3]);if(ext==L".csv")raw=serializeRows(r);auto opts=cliOptions(n,a,5);opts.originalExe=a[2];if(opts.omitDxa)r=exeOnlyCatalog(a[2],r);if((!opts.externalFont||opts.fontDxa)&&opts.subsetFont&&(!opts.font.empty()||!opts.fontMemory.empty()))for(const auto& row:extractAll(a[2]))opts.extraCharacters+=row.source;auto bytes=pack(readFile(a[2]),r,opts,raw);if(opts.fontDxa)exportExternalFont(a[4],r,opts);save(a[4],bytes);output("{\"packed\":true,\"rows\":"+std::to_string(r.size())+",\"bytes\":"+std::to_string(bytes.size())+",\"sha256\":\""+hash(bytes)+"\"}\n");return 0;}
    if(command==L"--unpack"&&n>=4){PE p(readFile(a[2]));auto r=unpack(p);auto h=payload(p);save(a[3],std::string((char*)h+h->text,h->textBytes));for(int i=4;i<n;++i){std::wstring k=a[i];if(++i>=n)throw std::runtime_error("Missing export path");if(k==L"--font-out"){save(a[i],std::string((char*)h+h->font,h->fontBytes));}else if(k==L"--settings-out"){StringMap s={{L"font",wide((char*)h+h->face)},{L"height",std::to_wstring(h->height)},{L"width",std::to_wstring(h->width)},{L"scale",std::to_wstring(h->scale)},{L"maxWidth",std::to_wstring(h->maxWidth)},{L"minScale",std::to_wstring(h->minScale)},{L"omitDxa",(h->reserved&4)?L"1":L"0"},{L"fontDxa",(h->reserved&8)?L"1":L"0"}};save(a[i],serialize(s));}else throw std::runtime_error("Unknown export option");}output("{\"unpacked\":true,\"rows\":"+std::to_string(r.size())+",\"font_bytes\":"+std::to_string(h->fontBytes)+"}\n");return 0;}
    output("MoeKuriTools.exe [GUI]\n--extract original.exe originals.txt [--omit-dxa 1|0]\n--filter-exe original.exe catalog.txt/csv output.txt/csv\n--dxa-unpack input.dxa output-folder\n--dxa-pack input-folder output.dxa\n--font-archive font.ttf/font.otf font.dxa\n--validate translation.txt\n--import-csv input.csv output.txt\n--export-csv input.txt output.csv\n--convert input.txt/csv/tsv/json output.txt/csv/tsv/json\n--pack original.exe translation.txt/csv/tsv/json output.exe [--font font.ttf] [--subset-font 1] [--omit-dxa 1|0] [--external-font 0|1] [--font-dxa 0|1] [--face family] [--height 0] [--width 0] [--scale 100] [--max-width 620] [--min-scale 70]\n--unpack patched.exe translation.txt [--font-out font.ttf] [--settings-out settings.json]\n--inspect patched.exe\n--self-test\n--gui-test report.json\n--language-list\n");return command==L"--help"?0:2;
}
}
int WINAPI wWinMain(HINSTANCE app,HINSTANCE,LPWSTR,int){int n=0;wchar_t** a=CommandLineToArgvW(GetCommandLineW(),&n);bool command=n>1;try{int result=0;if(command && std::wstring(a[1])==L"--gui-test" && n==3){gui::run(app,a[2]);}else if(command)result=cli(n,a);else gui::run(app);LocalFree(a);return result;}catch(const std::exception& e){if(command)output(std::string("ERROR: ")+e.what()+"\n");else MessageBoxW(0,ui::error(e.what()).c_str(),ui::tr(L"failed"),MB_OK|MB_ICONERROR);if(a)LocalFree(a);return 1;}}
